apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-aesq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-aesq
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-aesq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-aesq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-aesq
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-sltg-tenant/rhtap-demo-app/hacbs-test-project-aesq@sha256:4d24f978407f9831721f22f5854be6bbebd0355633d1b23bcdd3053abe60fe98
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
