apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-aesq
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-sltg-tenant/rhtap-demo-app/hacbs-test-project-aesq@sha256:4d24f978407f9831721f22f5854be6bbebd0355633d1b23bcdd3053abe60fe98
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
